#!/usr/bin/env bash
# init.sh - Initialize multi_run: manage workspace + generate compose

set -euo pipefail

# shellcheck source=script/lib.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/script/lib.sh"

NETWORK_CONFIG="${MULTI_ROOT}/.multi_network.yaml"

usage() {
    cat >&2 <<'EOF'
Usage: ./init.sh [-h] [OPTIONS] [path1 path2 ...]

Manage workspace and generate .multi_compose.yaml.

Commands:
  (no args)             Scan workspace/ → generate compose
  <path1> <path2> ...   Use given paths directly (skip workspace/)
  --add <path> ...      Add workspace symlinks
  --remove <name> ...   Remove workspace symlinks
  --list                List registered workspace

Options:
  -h, --help            Show this help

Network isolation:
  Create .multi_network.yaml to define network groups:

    groups:
      robot_a:
        - docker_ros_noetic
        - docker_ros1_bridge
      robot_b:
        - docker_ros2_humble

  Containers in the same group share a bridge network and can
  communicate. Different groups are isolated. Containers not
  listed in any group keep network_mode: host (default).

  A container can appear in multiple groups to bridge them.

Examples:
  ./init.sh --add ~/robot_ws/docker_ros_noetic ~/nav_ws/docker_ros2_humble
  ./init.sh --remove docker_ros_noetic
  ./init.sh --list
  ./init.sh                      # scan workspace/ → generate compose
  ./init.sh ~/ws_a/docker_ros_noetic ~/ws_b/docker_ros2_humble
EOF
    exit 0
}

# ── Workspace management ─────────────────────────────────────────────────────

_add_workspace() {
    local target_path
    target_path="$(cd "$1" && pwd -P)" || _error "Directory not found: $1"
    local name
    name="$(basename "${target_path}")"

    mkdir -p "${WORKSPACE_DIR}"

    if [[ -L "${WORKSPACE_DIR}/${name}" ]]; then
        _log "Already exists: ${name}"
    else
        ln -sf "${target_path}" "${WORKSPACE_DIR}/${name}"
        _log "Added: ${name} → ${target_path}"
    fi
}

_remove_workspace() {
    local name="$1"
    local link="${WORKSPACE_DIR}/${name}"

    if [[ -L "${link}" ]]; then
        rm -f "${link}"
        _log "Removed: ${name}"
    else
        _error "Not found: ${name}"
    fi
}

_list_workspace() {
    _log "Registered workspace:"
    if [[ -d "${WORKSPACE_DIR}" ]]; then
        local found=false
        for link in "${WORKSPACE_DIR}"/*; do
            [[ -L "${link}" ]] || continue
            found=true
            local name target
            name="$(basename "${link}")"
            target="$(readlink -f "${link}")"
            _log "  ${name} → ${target}"
        done
        [[ "${found}" == false ]] && _log "  (empty)"
    else
        _log "  (empty)"
    fi
}

# ── Compose generation ───────────────────────────────────────────────────────

_generate_compose() {
    local gen_paths=("$@")

    [[ ${#gen_paths[@]} -eq 0 ]] && _error "No workspace found. Use --add <path> or provide paths."

    # Parse network config if present
    declare -A network_map
    local used_networks=()
    if [[ -f "${NETWORK_CONFIG}" ]]; then
        _log "Loading network config: ${NETWORK_CONFIG}"
        while IFS='=' read -r ws_name net_list; do
            network_map["${ws_name}"]="${net_list}"
        done < <(python3 "${MULTI_ROOT}/script/parse_network_config.py" \
                     "${NETWORK_CONFIG}")
    fi

    cat > "${GENERATED_COMPOSE}" <<'HEADER'
# Auto-generated by init.sh — do not edit
services:
HEADER

    : > "${STATE_FILE}"

    for p in "${gen_paths[@]}"; do
        [[ -f "${p}/compose.yaml" ]] || _error "No compose.yaml in ${p}"

        # Ensure .env
        if [[ ! -f "${p}/.env" ]]; then
            if [[ -f "${p}/template/script/docker/setup.sh" ]]; then
                "${p}/template/script/docker/setup.sh" --base-path "${p}"
            else
                _error "No .env in ${p}"
            fi
        fi

        instance_id="$(_path_id "${p}")"

        # Resolve compose
        resolved=$(cd "${p}" && docker compose --env-file .env config 2>/dev/null) \
            || _error "Failed to resolve compose in ${p}"

        # Check if this workspace has network config
        local ws_name net_arg=""
        ws_name="$(basename "${p}")"
        if [[ -n "${network_map[${ws_name}]+x}" ]]; then
            net_arg="--networks ${network_map[${ws_name}]}"
            # Collect unique network names
            IFS=',' read -ra nets <<< "${network_map[${ws_name}]}"
            for net in "${nets[@]}"; do
                local already=false
                for existing in "${used_networks[@]}"; do
                    [[ "${existing}" == "${net}" ]] && already=true && break
                done
                [[ "${already}" == false ]] && used_networks+=("${net}")
            done
        fi

        # Extract devel service, rename, remove container_name
        # shellcheck disable=SC2086
        echo "${resolved}" | python3 "${MULTI_ROOT}/script/resolve_compose.py" \
            "${instance_id}" ${net_arg} \
            >> "${GENERATED_COMPOSE}"

        echo "${p}" >> "${STATE_FILE}"
        _log "Added: $(basename "${p}") → ${instance_id}"
    done

    # Append networks section if any groups are used
    if [[ ${#used_networks[@]} -gt 0 ]]; then
        printf "\nnetworks:\n" >> "${GENERATED_COMPOSE}"
        for net in "${used_networks[@]}"; do
            printf "  %s:\n    driver: bridge\n" "${net}" >> "${GENERATED_COMPOSE}"
        done
    fi

    _log "Generated: ${GENERATED_COMPOSE}"
    _log "Run ./run.sh to start."
}

# ── Main ─────────────────────────────────────────────────────────────────────

case "${1:-}" in
    -h|--help)
        usage
        ;;
    --add)
        shift
        [[ $# -eq 0 ]] && _error "Missing path. Usage: ./init.sh --add <path> ..."
        for p in "$@"; do _add_workspace "${p}"; done
        ;;
    --remove)
        shift
        [[ $# -eq 0 ]] && _error "Missing name. Usage: ./init.sh --remove <name> ..."
        for n in "$@"; do _remove_workspace "${n}"; done
        ;;
    --list)
        _list_workspace
        ;;
    *)
        # Collect paths
        paths=()
        if [[ $# -gt 0 ]]; then
            for arg in "$@"; do
                local_path="$(cd "${arg}" 2>/dev/null && pwd -P)" || _error "Directory not found: ${arg}"
                paths+=("${local_path}")
            done
        else
            mapfile -t paths < <(_get_workspace_paths)
        fi
        _generate_compose "${paths[@]}"
        ;;
esac
