#!/usr/bin/env bash
# init.sh - Generate merged compose from workspace

set -euo pipefail

# shellcheck source=lib.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/lib.sh"

usage() {
    cat >&2 <<'EOF'
Usage: ./init.sh [-h] [path1 path2 ...]

Generate .multi_compose.yaml from workspace/ symlinks or given paths.
Each workspace's compose.yaml is resolved and merged with unique service names.

Without arguments: scans workspace/ directory.
With arguments: uses given paths (ignores workspace/).

Options:
  -h, --help    Show this help

Examples:
  ./init.sh                                    # scan workspace/
  ./init.sh ~/ws_a/docker_ros_noetic ~/ws_b/docker_ros2_humble
EOF
    exit 0
}

[[ "${1:-}" =~ ^(-h|--help)$ ]] && usage

# Collect paths
paths=()
if [[ $# -gt 0 ]]; then
    for arg in "$@"; do
local_path="$(cd "${arg}" 2>/dev/null && pwd -P)" || _error "Directory not found: ${arg}"
        paths+=("${local_path}")
    done
else
    while IFS= read -r p; do
        [[ -n "${p}" ]] && paths+=("${p}")
    done < <(_get_workspace_paths)
fi

[[ ${#paths[@]} -eq 0 ]] && _error "No workspace found. Use ./add.sh or provide paths."

# Generate compose
cat > "${GENERATED_COMPOSE}" <<'HEADER'
# Auto-generated by init.sh — do not edit
services:
HEADER

: > "${STATE_FILE}"

for p in "${paths[@]}"; do
    [[ -f "${p}/compose.yaml" ]] || _error "No compose.yaml in ${p}"

    # Ensure .env
    if [[ ! -f "${p}/.env" ]]; then
        if [[ -f "${p}/docker_template/setup.sh" ]]; then
            "${p}/docker_template/setup.sh" --base-path "${p}"
        else
            _error "No .env in ${p}"
        fi
    fi

    instance_id="$(_path_id "${p}")"

    # Resolve compose
    resolved=$(cd "${p}" && docker compose --env-file .env config 2>/dev/null) \
        || _error "Failed to resolve compose in ${p}"

    # Extract devel service, rename, remove container_name
    echo "${resolved}" | python3 "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/script/resolve_compose.py" "${instance_id}" \
        >> "${GENERATED_COMPOSE}"

    echo "${p}" >> "${STATE_FILE}"
    _log "Added: $(basename "${p}") → ${instance_id}"
done

_log "Generated: ${GENERATED_COMPOSE}"
_log "Run ./run.sh to start."
